// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7JAhgDXmb-lHu9T1M5w32_t2IcbIOsY0',
    appId: '1:776317614159:web:c9ba216c8cb73bddec523a',
    messagingSenderId: '776317614159',
    projectId: 'notesappu',
    authDomain: 'notesappu.firebaseapp.com',
    storageBucket: 'notesappu.appspot.com',
    measurementId: 'G-C4QKTDJSE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ2PHyPYOPA9nVpiLmqUhEiT1u38BYJQM',
    appId: '1:776317614159:android:2247192da43e5d50ec523a',
    messagingSenderId: '776317614159',
    projectId: 'notesappu',
    storageBucket: 'notesappu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyttKGKxjo-yTt62GdiK3fUzn9ECrmESQ',
    appId: '1:776317614159:ios:d71bc4729bf3d772ec523a',
    messagingSenderId: '776317614159',
    projectId: 'notesappu',
    storageBucket: 'notesappu.appspot.com',
    iosBundleId: 'com.example.rideApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyttKGKxjo-yTt62GdiK3fUzn9ECrmESQ',
    appId: '1:776317614159:ios:d71bc4729bf3d772ec523a',
    messagingSenderId: '776317614159',
    projectId: 'notesappu',
    storageBucket: 'notesappu.appspot.com',
    iosBundleId: 'com.example.rideApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7JAhgDXmb-lHu9T1M5w32_t2IcbIOsY0',
    appId: '1:776317614159:web:038633dd0c3660d4ec523a',
    messagingSenderId: '776317614159',
    projectId: 'notesappu',
    authDomain: 'notesappu.firebaseapp.com',
    storageBucket: 'notesappu.appspot.com',
    measurementId: 'G-1C4WVFHQRQ',
  );
}
